apiVersion: v1
kind: Namespace
metadata:
  name:  dev3
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-memory-range
  namespace: dev3
spec:
  limits:
    - default:
        cpu: "500m" #not defined then 1 vCPU
        memory: "512Mi" #not defined then 512Mi
      defaultRange: #if not defined the it will take the max CPU and Memory
        cpu: "300m"
        memory: "256Mi"
      type: Container
  