apiVersion: v1
kind: Service
metadata:
  name:  clb-usermgmt-restapp-service
spec:
  selector:
    app:  usermgmt-restapp
  type:  LoadBalancer  #Default: CLB
  ports:
    - port: 80 
      targetPort:  8095