apiVersion: v1
kind: Service
metadata:
  name:  nlb-usermgmt-restapp-service
  labels:
    app: usermgmt-restapp
  annotations: #assume it as passing parameter to k8s
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  selector:
    app:  usermgmt-restapp
  type:  LoadBalancer  #Default: CLB
  ports:
    - port: 80 
      targetPort:  8095